### ISSUE TITLE
An error occurred while fine-tuning the model

### ISSUE THREAD

**Issue by volare1996** [PRBonn/segcontrast#8]
how to solve this error? Thanks!
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
Traceback (most recent call last):
  File "downstream_train.py", line 87, in <module>
    trainer.fit(model_sem_kitti)
  ．．．．．．
  File "/home/nudt/qianjia1126/20220407/segcontrast-main/data_utils/datasets/SemanticKITTIDataLoader.py", line 176, in __getitem__
    return self._get_augmented_item(index) if self.pre_training else self._get_item(index)
  File "/home/nudt/qianjia1126/20220407/segcontrast-main/data_utils/datasets/SemanticKITTIDataLoader.py", line 165, in _get_item
    points_set = np.delete(points_set, unlabeled, axis=0)

ValueError: boolean array argument obj to delete must be one dimensional and match the axis length of 49152

**Comment by nuneslu** [comment]
Hi, this dataloader was implemented specifically for SemanticKITTI, are you using it for another dataset? Could you print ```points_set.shape``` and ```unlabeled.shape``` and share here?

**Comment by volare1996** [comment]
Yes, thanks！
